baseURL = "https://aux-quatre-coins-de-paris.fr"
defaultContentLanguage = "en"
title = "Aux quatre coins de Paris"
theme = "auxquatrecoins"
googleAnalytics = "UA-86971850-1"

[params]
  themeColor = "#27478c"

[languages]
  [languages.en]
    catchPhrase = "Make the most of Paris!"
    languageName = "English"
    languageCode = "en-US"
  [languages.fr]
    catchPhrase = "Make the most of Paris fr!"
    languageName = "Français"
    languageCode = "fr-FR"
