baseURL = "https://aux-quatre-coins-de-paris.fr/"
defaultContentLanguage = "en"
title = "Aux quatre coins de Paris"
theme = "auxquatrecoins"

[languages]
  [languages.en]
    catchPhrase = "Make the most of Paris!"
    languageName = "English"
  [languages.fr]
    catchPhrase = "Make the most of Paris fr!"
    languageName = "Français"
